### ISSUE TITLE
A couple of missing capabilites for better SPV wallet/merchant solution

### ISSUE THREAD

**Issue by eye1** [bitcoin-sv-specs/brfc-merchantapi#3]
From a big picture perspective the use cases I know about and can't cover them with merchant API atm, but would like to are:

1) detect reorgs and check if your own affected transactions were also confirmed in the winning fork. In other words, reset unknown block hashes and re-do query transaction status
2) check how much fees are incoming transaction actually paying -> In other words fetching input transactions for the paying transaction 

One good thing about merchant API is that it is basically creating s standard. And if you can talk to miners with a standard protocol that in itself gives a lot of value, which people maybe don't see at this point. 

I think if a capability is SPV feature it fits in it. Maybe not in basic tier, but conceptually it's aligned. At the end of the day, a merchant needs an SPV powered wallet to operate.

**Comment by jadwahab** [comment]
@eye1 I'm not sure I understand your 2nd point, can you please elaborate on what you mean?
You want to check the amount of fees the other incoming transactions to the miner are paying?

**Comment by eye1** [comment]
From the top-level use case:

When a merchant/wallet receives transaction via P2P (or legacy even), it wants to check how much fee the transaction is paying. Based on that it can reject the transaction or assign different policies. For example, make utxos only available to be spent once the transaction which is paying low fees is actually mined and not before.

From technical requirements, the wallet needs all the complete transactions from which inputs are being spent so it can read the amounts and base on those calculate mining fees. 

So technically for a full SPV, I think it's a set of three things (raw transaction itself, merkle proofs and existing raw transactions from where the inputs originate)

There are two ways to achieve that:

a) sender provides those aside from raw transaction (if it has them)
b) receiver fetches that information when it is not provided via specific mApi capability

**Comment by jadwahab** [comment]
For SPV to work properly, yes the sender would have to send the raw tx, the txs for all inputs along with their merkle proofs in order for the receiver to have all they need to valdiate the tx.

The idea is that when anyone receives a tx, they must settle it on the blockchain and then they should get a merkle proof (from mAPI) when it gets included in a block(s). Then when they want to spend any of that tx's outpoints they would need to send that tx and it's merkle proof along with the newly created tx to whoever they want to send that payment to, and so on.

**Comment by jadwahab** [comment]
Also, ideally with BIP27x, the receiver of a payment should include the required fee in the `PaymentRequest` sent the to sender of the payment.

**Comment by eye1** [comment]
Yes, one is ideal and the other is a more pragmatic approach which anyone can start applying today. As we speak there is no such live protocol that would enforce that information to be exchanged. 

I think one should not exclude the other though.

**Comment by jadwahab** [comment]
If you want something to use today, what about WoC API?
[Get the tx for input(s)](https://developers.whatsonchain.com/#get-by-tx-hash)
[Get each of their merkle proofs](https://developers.whatsonchain.com/#get-merkle-proof)

**Comment by eye1** [comment]
Yes. Absolutely.

My suggestion is that mapi might cover it too as it seems aligned with something merchant/wallet would need in regards to SPV.

It's easier to talk with miners via more standardized protocols.
