### ISSUE TITLE
Stats collected during today's stress test - from two different miners

### ISSUE THREAD

**Issue by eye1** [bitcoin-sv-specs/brfc-merchantapi#4]
![image](https://user-images.githubusercontent.com/4639650/85543420-57671600-b61a-11ea-8c9f-691e1dc417c7.png)

I am sharing if it is useful. Maybe certain goals could be set to have a chance for a miner to prioritize certain mApi traffic (with SLA attached) over the rest. Also, some caching could be applied for status reading operations. 

The one capability that mostly affects user experience is broadcast.  

We can see from the chart response times with both miners increased 1000%

**Comment by jadwahab** [comment]
Thank you @eye1, this is very helpful. Would definitely be useful if you linked it on the refernce implementation [repo](https://github.com/bitcoin-sv/merchantapi-reference) for miners.
