### ISSUE TITLE
Transparency around limits 

### ISSUE THREAD

**Issue by mathiasrw** [bitcoin-sv-specs/brfc-merchantapi#8]
Is there any plans to add more information  to mAPI about how we need to construct transactions - like ancestor limits or max payload / transaction size? 

Including info about ancestor limit will let wallets/services adapt to the limits of the miner as it is key to select the best strategy for any service constructing multiple/many tx's in sequence.

It could be done by adding a generic "limits" next to "fees" so a payload might look like 

```
{
    "apiVersion": "1.2.0",
    "timestamp": "2020-11-12T13:17:47.7498672Z",
    "expiryTime": "2020-11-12T13:27:47.7498672Z",
    "minerId": "030d1fe5c1b560efe196ba40540ce9017c20daa9504c4c4cec6184fc702d9f274e",
    "currentHighestBlockHash": "45628be2fe616167b7da399ab63455e60ffcf84147730f4af4affca90c7d437e",
    "currentHighestBlockHeight": 234,
    "fees": [
        {
            "feeType": "standard",
            "miningFee": {
                "satoshis": 500,
                "bytes": 1000
            },
            "relayFee": {
                "satoshis": 250,
                "bytes": 1000
            }
        },
        {
            "feeType": "data",
            "miningFee": {
                "satoshis": 500,
                "bytes": 1000
            },
            "relayFee": {
                "satoshis": 250,
                "bytes": 1000
            }
        }
    ], 
    "limits": [
        {
            "limitType": "ancestor",
            "count": 1000
        }
    ]
}
```

**Comment by mathiasrw** [comment]
@jadwahab @shadders @asraha

Is this the right place to initiate dialogue? Is there an email list or forum that is better for inputs like this?

**Comment by jadwahab** [comment]
Hey @mathiasrw, thanks for your feedback. The best place for initiating dialogue would be the [telegram group](https://t.me/joinchat/JB6ZzktqwaiJX_5lzQpQIA) for mAPI. An addition concerning the ancestor limit would likely need to be addressed in conjunction with the Node team. We will take a look and get back to you soon. Cheers!

**Comment by mathiasrw** [comment]
@mantra774 - Oh - for sure. How the limits are made discoverable is not important! 

Please let me know if you hear about any improvements in this area. I suggested doing it as part of mapi as it has gained broad support in the ecosystem.

**Comment by mathiasrw** [comment]
Any news regarding this?

**Comment by matra774** [comment]
Yes, the latest release of MAPI exposes limits through a policy quote. See
https://github.com/bitcoin-sv-specs/brfc-merchantapi#1-get-policy-quote

V pon., 28. feb. 2022 15:46 je oseba Mathias Wulff ***@***.***>
napisala:

**Comment by mathiasrw** [comment]
Nice work getting this into a release!

<img width="865" alt="image" src="https://user-images.githubusercontent.com/1063454/196616356-90e22552-8f03-4575-9c4f-79a0baab714b.png">
